### PR TITLE
Adding a Tailor BOD fill script

### PR DESCRIPTION
**Pull request by djredman99**
Also adding a .gitignore file to eliminate the .venv folder which is a CodeSpaces generated folder (when developing inside codespaces)

### CODE REVIEW

**Comment by Reetus** [comment]
You need the header at the top of the file as per the instructions in the README.md...

If you macro is shard specific:

```py
# Name: Delucia Bulls
# Description: Walks around delucia taming bulls
# Author: Reetus
# Shard: OSI
```

Or if it era specific:

```py
# Name: Delucia Bulls
# Description: Walks around delucia taming bulls
# Author: Reetus
# Era: TOL
```

**Comment by djredman99** [comment]
yeah, I thought it was there but must have been deleted in my refactoring

**Comment by djredman99** [comment]
Also, it looks like it to me that the metadata file could be added to the .gitignore file and would be preferable.  You are editing the file in your workflow and local metadata files are just full of conflicts.

**Comment by djredman99** [comment]
@Reetus

**Pull request merged**
